version: "3.9"
services:
  redis:
    hostname: "redis-server"
    ports:
      - "6379:6379"
    image: "redis:alpine"
    networks:
      - backend
  
  flask_app-dev:
    container_name: messaging_api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/app
      - /var/log/messaging_api
    networks:
      - backend
      - frontend

networks:
  backend:
    driver: bridge
    internal: true
  
  frontend:
    driver: bridge
